id: P006838
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:53.459569
source_metadata:
  id: bdr:W8LS18712
  title: ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་རྩ་ཁྲིམས།
  author: ''
  volumes:
    a9d0d66ea1d8482ba188512dd11457a6:
      image_group_id: I8LS18714
      title: ''
      volume_number: 1
      total_pages: 99
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
